apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mus9as0ke-nodejs 
  janus-idp.io/tekton: mus9as0ke-nodejs
  backstage.io/kubernetes-id: mus9as0ke-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mus9as0ke-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml