apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: mus9as0ke-nodejs-gitops
  description: This is GitOps manifest for mus9as0ke-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=mus9as0ke-nodejs
    backstage.io/kubernetes-id: mus9as0ke-nodejs 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: rhtap-rhdh-qe/mus9as0ke-nodejs-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:mus9as0ke-nodejs
